### ISSUE TITLE
Not working in Samsung note 10 

### ISSUE THREAD

**Issue by Luisstevie** [judemanutd/AutoStarter#37]
I got an exception here. Activity Not found exception
` try {
                startIntent(context, PACKAGE_SAMSUNG_MAIN, PACKAGE_SAMSUNG_COMPONENT)
            } catch (e: Exception) {
                e.printStackTrace()
                return false
            }`

**Comment by judemanutd** [comment]
Hey @Luisstevie thanks for the notice, this library depends on crowd sourcing very heavily since one person doesn't have all the phones that can be tried and tested to figure out which package works, it would be great to have a pull request for the version of samsung phone that you are currently testing it on.

**Comment by chrisonline** [comment]
Hey @judemanutd !

See my comment to #33 it seems the activity name is wrong or was changed.

**Comment by judemanutd** [comment]
This should be resolved by https://github.com/judemanutd/AutoStarter/pull/69 but feel free to open this issue back up in case it does not
