### ISSUE TITLE
Problem with Huawei P10

### ISSUE THREAD

**Issue by giudon010** [judemanutd/AutoStarter#38]
Hello,
I just want to report a problem with Huawei P10.

In the "autoStartHuawei" method, if the intent "PACKAGE_HUAWEI_COMPONENT" exist and gets correctly called, but also exist the intent "PACKAGE_HUAWEI_COMPONENT_FALLBACK", the second one don't get called because the first one do not throw an exception.

Is this wanted?

Best regards, and thank you for your wonderful library

**Comment by judemanutd** [comment]
Hey @giudon010  thanks, the library essentially is looking for a combination of package names so if huawei changes their package names, there is a very good chance it would either not find the package or it would find 1 and not the next one because huawei shuffed them up, did the current setup of the library open up the autostart on the P10?

**Comment by giudon010** [comment]
Hello  @judemanutd, thank your for your answer.

No, the current setup doesn't work.

I try to explain better the trouble, because it's a "rare case", but it happens.

On My Huawei P10 (Android 8.0.0, EMUI 8.0.0), are available both Intents that you check with AutoStarter:

- private val PACKAGE_HUAWEI_COMPONENT = "com.huawei.systemmanager.optimize.process.ProtectActivity"
- private val PACKAGE_HUAWEI_COMPONENT_FALLBACK = "com.huawei.systemmanager.startupmgr.ui.StartupNormalAppListActivity"

The first one is still-present Intent, **but never used by the phone** because is unreachable from the Phone Settings (I think it is an Intent left wrongly by the old versions of Huawei smartphones), the second one is the real activity that I should view with AutoStarter, but it is never showed because AutoStarter find (wrongly) the first one.

A possible solution is simply to replace the most recent Intent with the old ones (I think that it could be a good solutions also for other manufacturers managed by AutoStarters).
To be more precise, in Huawei case, you should replace COMPONENT variables as follows:
- private val PACKAGE_HUAWEI_COMPONENT = "com.huawei.systemmanager.startupmgr.ui.StartupNormalAppListActivity"
- private val PACKAGE_HUAWEI_COMPONENT_FALLBACK = "com.huawei.systemmanager.optimize.process.ProtectActivity"

or, in alternative, try to check for both ones presences, something like:

>             try {
>                 startIntent(context, PACKAGE_HUAWEI_MAIN, PACKAGE_HUAWEI_COMPONENT)
>             } catch (e: Exception) {
>                 e.printStackTrace()
>             }
>             try {
>                     startIntent(context, PACKAGE_HUAWEI_MAIN, PACKAGE_HUAWEI_COMPONENT_FALLBACK)
>                 } catch (ex: Exception) {
>                     ex.printStackTrace()
>                     return false
>             }

I hope that my proposed solutions can help me and other developers too. Let me know what you think about it.

**Comment by judemanutd** [comment]
That actually helps alot, thanks for taking the time and debugging this. I'll probably implement that last suggestion that you made and keep both intents just so that it can work with older devices as well since that was the one that worked initially. I'll have to wait until the weekend to actually make a change and have it up but in the mean time if you can make a pull request instead that would be great.

**Comment by judemanutd** [comment]
This should be resolved by https://github.com/judemanutd/AutoStarter/pull/69 but feel free to open the issue if it is not.
