### ISSUE TITLE
How to check if got the permission successfully?

### ISSUE THREAD

**Issue by Hardikverma** [judemanutd/AutoStarter#49]
After we navigate the user to the setting how to check if user successfully provided the permission.

And secondly is there way by which we can scroll user to the app after navigating to setting or if there any way to sort app by alphabet that would be very helpful our app name starts with 'U' me myself got sick scrolling for that long how user would not be.

It would be highly appreciated if there could help.

i have integrated it in java, Working smoothly, Great work.

**Comment by judemanutd** [comment]
As described in https://github.com/judemanutd/AutoStarter/issues/4 these aren't standard apis provided by google so there is no public api that can be called to check the state, this is something your app needs to keep track of. Scrolling again isn't something I have looked at and doesn't seem likely because the library merely checks the phone to see if a package exists with a particular name and if so, then create an intent for it and start it. That is as far as it goes, PR's are always welcome if you do come up with a solution to this.
